#!/bin/sh
# YADM bootstrap script

# Initialize Package Manager for TMUX
if [ ! -d ~/.tmux/plugins/tpm ]; then
	git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# Initialize Plug-in Manager for VIM
if [ ! -f ~/.vim/autoload/plug.vim ]; then
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
