#!/bin/sh
# fluxbox startup-script

# add extra bin directory into the PATH
export PATH=$HOME/.fluxbox/bin:$PATH

# basic X server configuration
rundom -b -r -i 7200 -d 3600 "fbsetbg -R ~/.local/share/backgrounds"
picom -b --config ~/.config/picom/picom.conf

# basic application set
xautolock -time 6 -locker "alock -b shade -c glyph -i frame" -secure &
gpg-agent --sh --enable-ssh-support --daemon
skippy-xd --start-daemon &
urxvtd -f -q -o
dunst &

# delayed ignition startup
sh -c """sleep 1
	aero2 &
	anki &
	cbatticon -n -u 30 &
	claws-mail &
	keepassxc &
	orage &
#	parcellite &
	tinymount &
	viper-qt &
	volumeicon &
	windy &
	wpa_gui -t -q -m 5 &
	xpad -h &
	conky -d --config ~/.config/conky/conky.conf
	syslog-notify -u -c 25
""" &

exec fluxbox
