#!/bin/sh
# fluxbox startup-script

# add extra bin directory into the PATH
export PATH=$HOME/.fluxbox/bin:$PATH

# basic X server configuration
rundom -b -r -i 7200 -d 3600 "fbsetbg -R ~/.fluxbox/images/"
compton -b --config ~/.config/compton.conf

# basic application set
xautolock -time 6 -locker "alock -b shade -c glyph -i frame" -secure &
gpg-agent --sh --enable-ssh-support --daemon
skippy-xd --start-daemon &
urxvtd -f -q -o
dunst &

# delayed ignition startup
sh -c """sleep 1
	gtk3-nocsd cbatticon -n -u 30 &
	claws-mail &
	keepassx --minimize &
#	parcellite &
	pnmixer &
#	rssguard &
	tinymount &
	viper-qt &
	windy &
	wpa_gui -t -q -m 5 &
	xpad -h &
	conky -d --config ~/.config/conky/conky.conf
	syslog-notify -u
""" &

exec fluxbox
